conda activate pcifar100
python train.py -conf mobilenet_orig
python train.py -conf mobilenet_LRBS_p15_d2
python train.py -conf mobilenet_LRBS_p15_d4
python train.py -conf mobilenet_LRBS_p20_d2
python train.py -conf mobilenet_LRBS_p20_d4
python train.py -conf mobilenet_LRBS_p8_d2
python train.py -conf mobilenet_LRBS_p8_d4
python train.py -conf mobilenet_LR_p15_d2
python train.py -conf mobilenet_LR_p15_d4
python train.py -conf mobilenet_LR_p20_d2
python train.py -conf mobilenet_LR_p20_d4
python train.py -conf mobilenet_LR_p8_d2
python train.py -conf mobilenet_LR_p8_d4
python train.py -conf resnet18_orig
python train.py -conf resnet18_LRBS_p15_d2
python train.py -conf resnet18_LRBS_p15_d4
python train.py -conf resnet18_LRBS_p20_d2
python train.py -conf resnet18_LRBS_p20_d4
python train.py -conf resnet18_LRBS_p8_d2
python train.py -conf resnet18_LRBS_p8_d4
python train.py -conf resnet18_LR_p15_d2
python train.py -conf resnet18_LR_p15_d4
python train.py -conf resnet18_LR_p20_d2
python train.py -conf resnet18_LR_p20_d4
python train.py -conf resnet18_LR_p8_d2
python train.py -conf resnet18_LR_p8_d4
python train.py -conf vgg16_orig
python train.py -conf vgg16_LRBS_p15_d2
python train.py -conf vgg16_LRBS_p15_d4
python train.py -conf vgg16_LRBS_p20_d2
python train.py -conf vgg16_LRBS_p20_d4
python train.py -conf vgg16_LRBS_p8_d2
python train.py -conf vgg16_LRBS_p8_d4
python train.py -conf vgg16_LR_p15_d2
python train.py -conf vgg16_LR_p15_d4
python train.py -conf vgg16_LR_p20_d2
python train.py -conf vgg16_LR_p20_d4
python train.py -conf vgg16_LR_p8_d2
python train.py -conf vgg16_LR_p8_d4
